-- Tạo filegroup cho bảng Tài Khoản --
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_LoaiTK1
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_LoaiTK2
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_LoaiTK3
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_LoaiTK4
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_LoaiTK5

-- Tạo các file ánh xạ tới filegroup --
-- Note thay đường dẫn K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA bằng 1 đường dẫn khác trên local --
ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'LOAITK1',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\LOAITK\LOAITK1.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_LOAITK1

ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'LOAITK2',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\LOAITK\LOAITK2.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_LOAITK2

ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'LOAITK3',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\LOAITK\LOAITK3.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_LOAITK3

ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'LOAITK4',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\LOAITK\LOAITK4.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_LOAITK4

ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'LOAITK5',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\LOAITK\LOAITK5.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_LOAITK5

-- PARTITION FUNCTION --
CREATE PARTITION FUNCTION TAIKHOAN_THEOLOAI(VARCHAR(10))
AS RANGE LEFT
FOR VALUES(N'Nhan Vien', N'Doi Tac', N'Tai Xe', N'Khach Hang')
GO

-- PARTITION SCHEMA --
CREATE PARTITION SCHEME TAIKHOAN_THEOLOAI_SCHEME
AS
PARTITION TAIKHOAN_THEOLOAI
TO (FG_LOAITK1, FG_LOAITK2, FG_LOAITK3, FG_LOAITK4, FG_LOAITK5)
GO

-- Xóa khóa ngoại -- 
ALTER TABLE TAIXE DROP CONSTRAINT FK_TAIXE_TAIKHOAN
ALTER TABLE KHACHHANG DROP CONSTRAINT FK_KHACHHANG_TAIKHOAN
ALTER TABLE NHANVIEN DROP CONSTRAINT FK_NHANVIEN_TAIKHOAN
ALTER TABLE DOITAC DROP CONSTRAINT FK_DOITAC_TAIKHOAN

-- Xóa khóa chính, add lại noncluster index --
ALTER TABLE TAIKHOAN
DROP CONSTRAINT PK_TaiKhoan

ALTER TABLE TAIKHOAN
ADD CONSTRAINT PK_TaiKhoan PRIMARY KEY 
NONCLUSTERED(TenTaiKhoan)
ON [PRIMARY]

-- Add lại khóa ngoại -- 
ALTER TABLE TAIXE ADD CONSTRAINT FK_TAIXE_TAIKHOAN
foreign key (TenTaiKhoanTaiXe)
references TAIKHOAN(TenTaiKhoan)
ALTER TABLE DOITAC ADD CONSTRAINT FK_DOITAC_TAIKHOAN
foreign key (TenTaiKhoanDT)
references TAIKHOAN (TenTaiKhoan)
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_TAIKHOAN
foreign key (TaiKhoanNV)
references TaiKhoan (TenTaiKhoan)
ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KHACHHANG_TAIKHOAN
foreign key (TenTaiKhoanKH)
references TaiKhoan (TenTaiKhoan)

-- Tạo cluster index trên thuộc tính cần chia, ở đây là loại tài khoản --
CREATE CLUSTERED INDEX IX_TAIKHOAN_THEOLOAI
ON TAIKHOAN
(
	LOAITAIKHOAN
) ON TAIKHOAN_THEOLOAI_SCHEME(LOAITAIKHOAN)