-- Tạo filegroup cho bảng Tài Khoản --
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_TinhTrang1
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_TinhTrang2
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_TinhTrang3
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_TinhTrang4
ALTER DATABASE CSDLNC2 ADD FILEGROUP FG_TinhTrang5

-- Tạo các file ánh xạ tới filegroup --
-- Note thay đường dẫn K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA bằng 1 đường dẫn khác trên local --
ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'TINHTRANG1',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\TINHTRANG\TINHTRANG1.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_TinhTrang1

ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'TINHTRANG2',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\TINHTRANG\TINHTRANG2.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_TinhTrang2

ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'TINHTRANG3',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\TINHTRANG\TINHTRANG3.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_TinhTrang3

ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'TINHTRANG4',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\TINHTRANG\TINHTRANG4.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_TinhTrang4

ALTER DATABASE CSDLNC2 ADD FILE (
	NAME = 'TINHTRANG5',
	FILENAME = 'K:\HCMUS Tools\MSSQL15.MSSQLSERVER01\MSSQL\DATA\CSDLNC2\TINHTRANG\TINHTRANG5.ndf',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_TinhTrang5

-- PARTITION FUNCTION --
CREATE PARTITION FUNCTION TinhTrang_THEOLOAI(NVARCHAR(20))
AS RANGE LEFT
FOR VALUES(N'Cho nhan', N'Dang chuan bi', N'Dang van chuyen', N'Hoan tat')
GO

-- PARTITION SCHEMA --
CREATE PARTITION SCHEME TinhTrang_THEOLOAI_SCHEME
AS
PARTITION TinhTrang_THEOLOAI
TO (FG_TinhTrang1, FG_TinhTrang2, FG_TinhTrang3, FG_TinhTrang4, FG_TinhTrang5)
GO

-- Tạo cluster index trên thuộc tính cần chia, ở đây là loại tài khoản --
CREATE CLUSTERED INDEX IX_TinhTrang_THEOLOAI
ON TinhTrangDonHang
(
	TinhTrangDonHang
) ON TinhTrang_THEOLOAI_SCHEME(TinhTrangDonHang)

